// Character Points Types

export type CharacterCategory = "discipline" | "responsibility" | "leadership" | "courtesy" | "integrity" | "teamwork" | "attendance" | "appearance" | "safety" | "religious"

export interface CharacterCategoryRecord {
  id: string
  name: string
  description?: string
  color: string
  icon?: string
  displayOrder: number
  status: "active" | "inactive"
  createdAt: string
  updatedAt: string
}

export interface BehaviorType {
  id: string
  categoryId: string
  name: string
  description?: string
  pointValue: number
  direction: "positive" | "negative"
  severity?: SeverityLevel
  requiresApproval: boolean
  requiresCounseling: boolean
  status: "active" | "inactive"
  createdAt: string
  updatedAt: string
}

export type SeverityLevel = "information" | "minor" | "moderate" | "major" | "critical"

export interface CharacterEvent {
  id: string
  name: string
  description?: string
  date: string
  location?: string
  organizer?: string
  academicYearId: string
  semesterId?: string
  status: "scheduled" | "ongoing" | "completed" | "cancelled"
  createdAt: string
  updatedAt: string
}

export interface CharacterRecord {
  id: string
  studentId: string
  behaviorTypeId: string
  eventId?: string
  date: string
  reporterId: string
  description?: string
  evidence?: string
  status: RecordStatus
  remarks?: string
  approvedBy?: string
  approvedAt?: string
  createdAt: string
  updatedAt: string
}

export type RecordStatus = "draft" | "submitted" | "reviewed" | "approved" | "archived"

export interface StudentCharacterSummary {
  studentId: string
  academicYearId: string
  semesterId?: string
  positivePoints: number
  negativePoints: number
  netScore: number
  totalRecords: number
  positiveRecords: number
  negativeRecords: number
  highestAchievement?: {
    behaviorTypeId: string
    name: string
    pointValue: number
  }
  mostFrequentViolation?: {
    behaviorTypeId: string
    name: string
    count: number
  }
  recentActivities: CharacterRecord[]
}

// Search and filter
export interface CharacterFilter {
  academicYearId?: string
  semesterId?: string
  classId?: string
  categoryId?: string
  behaviorTypeId?: string
  severity?: SeverityLevel
  reporterId?: string
  dateRange?: {
    start: string
    end: string
  }
  status?: RecordStatus
  direction?: "positive" | "negative"
}

// Statistics
export interface CharacterStatistics {
  totalPositivePoints: number
  totalNegativePoints: number
  totalRecords: number
  averagePoints: number
  mostAwardedCategory: string
  mostViolationCategory: string
  studentsRequiringAttention: string[]
  topPositiveStudents: {
    studentId: string
    name: string
    points: number
  }[]
}

export interface ClassCharacterSummary {
  classId: string
  className: string
  statistics: CharacterStatistics
  students: {
    studentId: string
    name: string
    positivePoints: number
    negativePoints: number
    netScore: number
  }[]
}

// Report
export interface CharacterReport {
  id: string
  type: "student" | "class" | "behavior" | "category"
  studentId?: string
  classId?: string
  academicYearId: string
  semesterId?: string
  generatedBy: string
  generatedAt: string
  data: Record<string, unknown>
}

// Category colors
export const CATEGORY_COLORS: Record<CharacterCategory, string> = {
  discipline: "#3B82F6",
  responsibility: "#10B981",
  leadership: "#F59E0B",
  courtesy: "#EC4899",
  integrity: "#8B5CF6",
  teamwork: "#06B6D4",
  attendance: "#EF4444",
  appearance: "#F97316",
  safety: "#6366F1",
  religious: "#84CC16",
}

// Counseling recommendation
export interface CounselingRecommendation {
  studentId: string
  reason: string
  severity: SeverityLevel
  suggestedAction: string
  autoGenerated: boolean
  approved: boolean
  approvedBy?: string
}
