// Hooks barrel export
export * from "./useAcademicYear"
export * from "./useStudents"
export * from "./useDashboardStats"
export * from "./useFilters"
export { useAuth } from "./useAuth"
export { useSettings, useAcademicYear as useAcademicYearFromSettings } from "./useSettings"
export { useCommand } from "./useCommand"
export { useAttendance, useAttendanceRecap } from "./useAttendance"
export { useAssessment, useAssessmentSession } from "./useAssessment"
export { useCharacter, useCharacterDashboard } from "./useCharacter"
